"""Create reusable factorized tokens from ABC melody segments."""

from __future__ import annotations

import re


# ABC durations supported here include:
# 2      -> twice the default duration
# 3/2    -> one and a half times the default duration
# /2     -> half the default duration
# /4     -> quarter of the default duration
# / or // -> shortened ABC duration notation
DURATION_PATTERN = r"(?:\d+/\d*|/\d+|/+|\d+)"


NOTE_PATTERN = rf"""
    [\^_=]*                     # accidentals: sharp, flat or natural
    [A-Ga-gzZxX]                # note or rest
    [',]*                       # octave modifiers
    (?:{DURATION_PATTERN})?     # optional duration
"""


NOTE_EVENT_RE = re.compile(
    NOTE_PATTERN,
    re.VERBOSE,
)


# These are generated by abc_utils.py during normalization.
#
# Requiring an underscore prevents musical groups such as [GB]
# from being confused with metadata.
STRUCTURAL_DIRECTIVE_PATTERN = (
    r"\[[A-Z][A-Za-z0-9]*(?:_[A-Za-z0-9#b/]+)+\]"
)


MUSIC_TOKEN_RE = re.compile(
    rf"""
    (?P<directive>
        {STRUCTURAL_DIRECTIVE_PATTERN}
    )

    |

    (?P<ending>
        \[
        (?P<ending_number>\d+)
    )

    |

    (?P<multinote>
        \[
        (?P<multinote_content>[^\]\n]+)
        \]
        (?P<multinote_duration>{DURATION_PATTERN})?
    )

    |

    (?P<repeat_end_start>
        :\|\|:
        |
        ::
    )

    |

    (?P<repeat_start>
        \|:
    )

    |

    (?P<repeat_end>
        :\|
    )

    |

    (?P<final_bar>
        \|\]
    )

    |

    (?P<double_bar_start>
        \[\|
    )

    |

    (?P<double_bar>
        \|\|
    )

    |

    (?P<bar>
        \|
    )

    |

    (?P<tuplet>
        \(
        (?P<tuplet_spec>
            \d+
            (?::\d+){{0,2}}
        )
    )

    |

    (?P<note>
        {NOTE_PATTERN}
    )
    """,
    re.VERBOSE,
)


def append_group_boundary(tokens: list[str]) -> None:
    """Append one group boundary without creating duplicates."""

    if not tokens:
        return

    if tokens[-1] == "[GROUP_BOUNDARY]":
        return

    tokens.append("[GROUP_BOUNDARY]")


def previous_token_allows_group_boundary(tokens: list[str]) -> bool:
    """
    Return whether whitespace probably separates two musical groups.

    We add a group boundary after a note or simultaneous-note group, but
    not after bars, repeats, directives or segment markers.
    """

    if not tokens:
        return False

    previous = tokens[-1]

    return (
        previous.startswith("[EVENT_")
        or previous == "[MULTI_END]"
        or previous.startswith("[MULTI_DURATION_")
    )


def append_multinote_group(
    tokens: list[str],
    content: str,
    duration: str | None,
) -> None:
    """
    Tokenize simultaneous notes written inside square brackets.

    For example:

        [G2B2]

    becomes:

        [MULTI_START]
        [EVENT_G2]
        [EVENT_B2]
        [MULTI_END]
    """

    note_events = [
        match.group(0)
        for match in NOTE_EVENT_RE.finditer(content)
    ]

    if not note_events:
        # Preserve the existence of an unsupported bracketed construct
        # instead of incorrectly splitting its letters into notes.
        tokens.append("[UNPARSED_BRACKET_GROUP]")
        return

    tokens.append("[MULTI_START]")

    for event in note_events:
        tokens.append(f"[EVENT_{event}]")

    tokens.append("[MULTI_END]")

    # ABC may place one duration after the complete simultaneous group,
    # for example [CEG]2.
    if duration:
        tokens.append(f"[MULTI_DURATION_{duration}]")


def tokenize_melody_events(melody: str) -> list[str]:
    """Split an ABC melody into reusable musical and structural tokens."""

    tokens: list[str] = []
    previous_end = 0

    for match in MUSIC_TOKEN_RE.finditer(melody):
        token_type = match.lastgroup

        text_between = melody[
            previous_end:match.start()
        ]

        current_is_musical_event = token_type in {
            "note",
            "multinote",
        }

        if (
            current_is_musical_event
            and any(character.isspace() for character in text_between)
            and previous_token_allows_group_boundary(tokens)
        ):
            append_group_boundary(tokens)

        if token_type == "directive":
            # Preserve metadata such as:
            # [METER_CHANGE_2_4]
            # [KEY_CHANGE_D]
            # [PART_A]
            tokens.append(match.group(0))

        elif token_type == "ending":
            ending_number = match.group("ending_number")
            tokens.append(f"[ENDING_{ending_number}]")

        elif token_type == "multinote":
            append_multinote_group(
                tokens=tokens,
                content=match.group("multinote_content"),
                duration=match.group("multinote_duration"),
            )

        elif token_type == "repeat_end_start":
            tokens.append("[REPEAT_END]")
            tokens.append("[REPEAT_START]")

        elif token_type == "repeat_start":
            tokens.append("[REPEAT_START]")

        elif token_type == "repeat_end":
            tokens.append("[REPEAT_END]")

        elif token_type == "final_bar":
            tokens.append("[FINAL_BAR]")

        elif token_type == "double_bar_start":
            tokens.append("[DOUBLE_BAR_START]")

        elif token_type == "double_bar":
            tokens.append("[DOUBLE_BAR]")

        elif token_type == "bar":
            tokens.append("[BAR]")

        elif token_type == "tuplet":
            tuplet_spec = match.group("tuplet_spec")
            normalized_spec = tuplet_spec.replace(":", "_")
            tokens.append(f"[TUPLET_{normalized_spec}]")

        elif token_type == "note":
            event = match.group(0)
            tokens.append(f"[EVENT_{event}]")

        previous_end = match.end()

    return tokens


def create_factorized_sequence(song: dict) -> list[str]:
    """Create a factorized token sequence for one processed song."""

    sequence = list(song["metadata_tokens"])

    for segment in song["segments"]:
        sequence.append("[SEGMENT_START]")
        sequence.append(
            f"[CHORD_{segment['chord']}]"
        )

        sequence.extend(
            tokenize_melody_events(
                segment["melody_normalized"]
            )
        )

        sequence.append("[SEGMENT_END]")

    return sequence