"""Run the complete preprocessing pipeline from the project root."""

from __future__ import annotations
import os
import argparse
from pathlib import Path
import subprocess
import sys

# Model Imports
# from src.models.unigram import UnigramModel
# from src.models.ngram import NGramModel
# from src.models.lstm import LSTMModel
from src.models.bert import BertPretrainedFineTuner

# Import load_jsonl from your create_splits.py
from src.create_splits import load_jsonl


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run ABC preprocessing, splitting and fixed masking."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("ABC_cleaned"),
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Use a small number such as 20 for a pilot run.",
    )
    return parser.parse_args()


def run(command: list[str]) -> None:
    print("\n$", " ".join(command))
    subprocess.run(command, check=True)


def load_data_splits(version: str) -> tuple[list[list[str]], list[list[str]]]:
    """
    Loads the processed JSONL splits and extracts the token sequences 
    for the specified representation version.
    """
    # Load the JSONL files generated by create_splits.py
    train_records = load_jsonl(Path("data/splits/train.jsonl"))
    eval_records = load_jsonl(Path("data/splits/validation.jsonl"))

    # Determine which dictionary key holds the tokens
    sequence_field = f"{version}_sequence_tokens"

    # Extract just the sequence lists
    train_sequences = [record[sequence_field] for record in train_records]
    eval_sequences = [record[sequence_field] for record in eval_records]

    return train_sequences, eval_sequences


def main() -> None:
    args = parse_args()
    script_directory = Path(__file__).resolve().parent

    preprocess_command = [
        sys.executable,
        str(script_directory / "preprocess_abc.py"),
        "--input",
        str(args.input),
    ]
    if args.limit is not None:
        preprocess_command.extend(["--limit", str(args.limit)])

    run(preprocess_command)
    run(
        [
            sys.executable,
            str(script_directory / "create_splits.py"),
        ]
    )
    run(
        [
            sys.executable,
            str(script_directory / "create_masked_examples.py"),
        ]
    )

    print("\nPipeline finished successfully.")
    print("Inspect data/processed/tokenization_examples.txt first.")

    print("Loading data splits...")
    train_atomic, eval_atomic = load_data_splits(version="atomic")
    train_factorized, eval_factorized = load_data_splits(version="factorized")

    # 2. Instantiate Transfer Learning BERT Models
    atomic_bert = BertPretrainedFineTuner(
        name="BERT_Transfer_Atomic",
        is_factorized=False,
        output_dir="./results_bert_transfer_atomic",
    )

    factorized_bert = BertPretrainedFineTuner(
        name="BERT_Transfer_Factorized",
        is_factorized=True,
        output_dir="./results_bert_transfer_factorized",
    )

    # 3. Fit Models 
    # Notice lowered batch size to 16 for heavier pre-trained weights.
    # If using --limit, lower epochs and batch size to avoid crashing on tiny datasets.
    epochs = 1 if args.limit else 5
    batch_size = 4 if args.limit else 16

    print(f"\nFine-tuning Pre-trained BERT on Atomic tokens (Epochs: {epochs}, Batch: {batch_size})...")
    atomic_bert.fit(train_atomic, epochs=epochs, batch_size=batch_size)

    print(f"\nFine-tuning Pre-trained BERT on Factorized tokens (Epochs: {epochs}, Batch: {batch_size})...")
    factorized_bert.fit(train_factorized, epochs=epochs, batch_size=batch_size)

    # 4. Universal Model List for Evaluation
    models_to_evaluate = [
        # UnigramModel("Unigram"),
        # NGramModel("NGram"),
        atomic_bert,
        factorized_bert,
    ]

    # 5. Run Evaluation Loop (Masked Accuracy & Plausibility Analysis)
    for model in models_to_evaluate:
        print(f"\nEvaluating {model.name}...")

        sample_seq = (
            eval_atomic[0]
            if not getattr(model, "is_factorized", False)
            else eval_factorized[0]
        )
        target_idx = 2 

        try:
            top_k_preds = model.predict_top_k(sample_seq, target_index=target_idx, k=5)
            print(f"Top 5 predictions for index {target_idx}: {top_k_preds}")
        except Exception as e:
            print(f"Evaluation encountered an error: {e}")


if __name__ == "__main__":
    main()